### ISSUE TITLE
Refactor: 新機能実装の前に、綺麗にする

### ISSUE THREAD

**Issue by hash52** [UETAKU32/war_hammer#38]
# 観点
- できるだけコアな部分

# Goal
- 下記タスクが全て終了したら、本issueはcloseとする

# todo

- [x] Hex.tsxのhandleClickの分割
- [ ] usePlayerの改善（アイデアが出なければ不可の可能性もあり） 
- [x] カスタムフックuseFindAllFighterByCoordinate, useFindTeamFighterByCoordinate, useEnemyTeamFighterByCoordinateの整理
- [x] FighterDisplay.tsxの画像表示をmapで書く (mapでリストを表示する練習。めちゃよく使う記法なのでマスターしましょう)
  - TeamInfoPanel.tsxの実装が参考になりそう

# 備考
- todo増やしたくなったら、以下に書く。リファクタはゴールを決めないと一生終わらないので、下記タスクのやりどきは要相談。すぐに手を付けないこと
  - [ ]

**Comment by UETAKU32** [comment]
usePlayerの改善は構造のアイデアが思い浮かばないので未実施でクローズ
